connectionString = "" /*define it without def to make it global. https://stackoverflow.com/questions/45514585/exception-while-executing-groovy-script-from-jenkinsfile-groovy-lang-missingprop*/
def uccode
def lockParams

def versionText
def versionValue

pipeline {
    agent {
        label 'bdd'
    }
    environment {
        Storage = credentials('Storage_Trade_CiBot')
        /* логин и пароль разделенные двоеточием:*/
        /* Storage - login:pass*/
        /* Storage_Usr - логин*/
        /* Storage_Psw - пароль*/
    }
    
    stages {
        stage ('Обновление тестового контура'){
            steps {
                timestamps {
                    script {
                        connectionString = "\"/S${env.Server1C}\\${env.Database1C}\""
                        uccode = "\"123\""
                        lockParams = "-lockmessage \"base is blocked\" -lockuccode ${uccode}"

                        versionText = readFile encoding: 'UTF-8', file: 'src/cf/VERSION'
                        versionValue = (versionText =~ /<VERSION>(.*)<\/VERSION>/)[0][1]
                    }
                    
                    cmd("oscript --version") 
                    cmd("deployka session lock -ras ${env.ServerRAS} -db ${env.Database1C} ${lockParams}")
                    cmd("deployka session kill -ras ${env.ServerRAS} -db ${env.Database1C} ${lockParams}")
                    cmd("deployka loadrepo ${connectionString} \"${env.StoragePath}\" -storage-user ${env.Storage_Usr} -storage-pwd ${env.Storage_Psw} -uccode \"123\" -storage-ver ${versionValue}")
                    cmd("deployka dbupdate ${connectionString} -allow-warnings -uccode \"123\"")
                    cmd("deployka session unlock -ras ${env.ServerRAS} -db ${env.Database1C}")
                }
            }
        }
    }
}
def cmd(command) {
    if (isUnix()) {
        sh "${command}"
    } else {
        bat "chcp 65001\n${command}"
    }
} 